name: CI Pipeline

# Define when the workflow should run
on:
  push:
    branches:
      - main  # Trigger only when changes are pushed to the 'main' branch

jobs:

  sync-dynatrace:
    # Specify the type of machine to run this job
    runs-on: ubuntu-latest

    steps:
      # Use a custom Docker image for Dynatrace configuration
      - name: Configure Dynatrace
        uses: docker://dynatrace/dynatrace-configuration-as-code:${{ secrets.MONACO_IMAGE_VERSION }}
        env:
          TENANT_URL: ${{ secrets.DT_PLATFORM_TENANT_URL }}
          TENANT_TOKEN: ${{ secrets.DT_API_TOKEN }}
          CLIENT_ID: ${{ secrets.DT_OAUTH_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DT_OAUTH_CLIENT_SECRET }}
        run: |
          # Run monaco for easytrade original configs
          monaco deploy ./easytrade/monaco/manifest.yaml --project application -e dev --dry-run
          monaco deploy ./easytrade/monaco/manifest.yaml --project application -e dev
